language: cpp

cache:
  directories:
    - /tmp/z3cache

addons:
  apt:
    sources: &default_sources
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages: &default_packages
      - ninja-build
      - re2c

env:
  global:
    - Z3_VERSION=4.8.9

before_script:
  - |
    if [ $TRAVIS_OS_NAME = linux ]; then
      if [ ! -d /tmp/z3cache/z3-$Z3_VERSION-x64-ubuntu-16.04 ] ; then
        rm -fr /tmp/z3cache
        mkdir /tmp/z3cache
        wget https://github.com/Z3Prover/z3/releases/download/z3-$Z3_VERSION/z3-$Z3_VERSION-x64-ubuntu-16.04.zip -O /tmp/z3.zip
        pushd /tmp
        unzip z3.zip
        mv z3-* z3cache
        popd
      fi
      sudo cp /tmp/z3cache/z3-$Z3_VERSION*/bin/libz3.so /usr/lib
      sudo cp /tmp/z3cache/z3-$Z3_VERSION*/include/* /usr/include
    fi

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
          -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER
          -DCMAKE_CXX_FLAGS=$CMAKE_CXX_FLAGS
          -GNinja
          ..
  - ninja
  - ninja check

matrix:
  include:
    - env: CMAKE_CXX_COMPILER=g++-10 CMAKE_BUILD_TYPE=Debug
      os: linux
      dist: focal
      addons: &gcc10
        apt:
          packages:
            - *default_packages
            - g++-10

    - env: CMAKE_CXX_COMPILER=g++-10 CMAKE_BUILD_TYPE=Release
      os: linux
      dist: focal
      addons: *gcc10

    - env: CMAKE_CXX_COMPILER=clang++-10 CMAKE_BUILD_TYPE=Debug CMAKE_CXX_FLAGS=-fsanitize=address,undefined
      os: linux
      dist: focal
      addons: &clang10
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - *default_packages
            - clang-10

    - env: CMAKE_CXX_COMPILER=clang++-10 CMAKE_BUILD_TYPE=Release
      os: linux
      dist: focal
      addons: *clang10

    - env: CMAKE_CXX_COMPILER=clang++-11 CMAKE_BUILD_TYPE=Debug CMAKE_CXX_FLAGS=-fsanitize=address,undefined
      os: linux
      dist: focal
      addons: &clang11
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - *default_packages
            - clang-11

    - env: CMAKE_CXX_COMPILER=clang++-11 CMAKE_BUILD_TYPE=Release
      os: linux
      dist: focal
      addons: *clang11

    - env: CMAKE_BUILD_TYPE=Debug CMAKE_CXX_FLAGS=-fsanitize=address,undefined
      os: osx
      osx_image: xcode12.2
      addons: &mac
        homebrew:
          packages:
            - ninja
            - re2c
            - z3
          update: true

    - env: CMAKE_BUILD_TYPE=Release
      os: osx
      osx_image: xcode12.2
      addons: *mac
