name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.compiler }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:         [ubuntu-20.04]
        compiler:   [g++-10, g++-11, clang++-12]
        build_type: [Release, Debug]
        include:
          - os: macos-latest
            compiler: clang++
            build_type: Release
          - os: macos-latest
            compiler: clang++
            build_type: Debug

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          wget -O- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main"
          sudo apt-get update
          sudo apt-get install z3 re2c ninja-build clang-12 g++-11

      - name: Install dependencies (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew install z3 re2c ninja

      - name: Compile
        run: ./.github/scripts/build.sh

      - name: Run Tests
        run: ninja check
        working-directory: build

    env:
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}
      CMAKE_CXX_COMPILER: ${{ matrix.compiler }}
      CMAKE_CXX_FLAGS: "-fsanitize=address,undefined"
