name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.compiler }} ${{ matrix.build_type }} ${{ matrix.cache }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:         [ubuntu-24.04]
        compiler:   [g++-14, clang++-21, clang++-22]
        build_type: [Release, Debug]
        cache:      ['', Redis]
        include:
          - os: macos-15
            compiler: clang++
            build_type: Release
          - os: macos-15
            compiler: clang++
            build_type: Debug

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          wget -O- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          if [[ ${{ matrix.compiler }} == "clang++-21" ]]; then
            sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-21 main"
          fi
          if [[ ${{ matrix.compiler }} == "clang++-22" ]]; then
            sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main"
          fi
          sudo apt-get update
          sudo apt-get install z3 re2c ninja-build
          if [[ ${{ matrix.compiler }} == "clang++-21" ]]; then
            sudo apt-get install clang++-21
          fi
          if [[ ${{ matrix.compiler }} == "clang++-22" ]]; then
            sudo apt-get install clang++-22
          fi
          if [[ "${{ matrix.cache }}" == "Redis" ]]; then
            sudo apt-get install libhiredis-dev
          fi

      - name: Install dependencies (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew install z3 re2c ninja

      - name: Compile
        run: ./.github/scripts/build.sh

      - name: Run Tests
        run: ninja check
        working-directory: build

    env:
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}
      CMAKE_CXX_COMPILER: ${{ matrix.compiler }}
      CMAKE_CXX_FLAGS: "-fsanitize=address,undefined -fno-sanitize-recover=all"
